name: CI-Tests
on: [push]

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install poetry
        run: pip install poetry

      - name: Install deps
        run: poetry install

      - name: Run Unit tests
        run: poetry run pytest tests/

      - name: Integration Test
        run: |
          ./scripts/run-integration-test.sh